/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/confirmDialog/index.vue')['default']
    Construction: typeof import('./src/components/Construction/index.vue')['default']
    Date: typeof import('./src/components/myForm/date.vue')['default']
    DateRange: typeof import('./src/components/myForm/dateRange.vue')['default']
    DateRangeWithTime: typeof import('./src/components/myForm/dateRangeWithTime.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Input: typeof import('./src/components/myForm/input.vue')['default']
    MaskInput: typeof import('./src/components/myForm/maskInput.vue')['default']
    MultipleSelect: typeof import('./src/components/myForm/multipleSelect.vue')['default']
    MyBanner: typeof import('./src/components/myBanner/index.vue')['default']
    MyDialog: typeof import('./src/components/myDialog/index.vue')['default']
    MyFixedPage: typeof import('./src/components/myFixedPage/index.vue')['default']
    MyPagination: typeof import('./src/components/myPagination/index.vue')['default']
    MyTooltip: typeof import('./src/components/myTooltip/index.vue')['default']
    Radio: typeof import('./src/components/myForm/radio.vue')['default']
    RightPanel: typeof import('./src/components/rightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/myForm/select.vue')['default']
    Slider: typeof import('./src/components/myForm/slider.vue')['default']
    TextToInput: typeof import('./src/components/textToInput/index.vue')['default']
    TextToSelect: typeof import('./src/components/textToSelect/index.vue')['default']
    TreeSelect: typeof import('./src/components/myForm/treeSelect.vue')['default']
  }
}
